const data = `<div class="Backquote keys ch"></div>
<div class="Digit1 keys ch"></div>
<div class="Digit2 keys ch"></div>
<div class="Digit3 keys ch"></div>
<div class="Digit4 keys ch"></div>
<div class="Digit5 keys ch"></div>
<div class="Digit6 keys ch"></div>
<div class="Digit7 keys ch"></div>
<div class="Digit8 keys ch"></div>
<div class="Digit9 keys ch"></div>
<div class="Digit0 keys ch"></div>
<div class="Minus keys ch"></div>
<div class="Equal keys ch"></div>
<div class="Backspace keys">&lArr;</div>
<div class="Tab keys">&rlarr;</div>
<div class="KeyQ keys ch"></div>
<div class="KeyW keys ch"></div>
<div class="KeyE keys ch"></div>
<div class="KeyR keys ch"></div>
<div class="KeyT keys ch"></div>
<div class="KeyY keys ch"></div>
<div class="KeyU keys ch"></div>
<div class="KeyI keys ch"></div>
<div class="KeyO keys ch"></div>
<div class="KeyP keys ch"></div>
<div class="BracketLeft keys ch"></div>
<div class="BracketRight keys ch"></div>
<div class="Backslash keys ch"></div>
<div class="CapsLock keys">Caps</div>
<div class="KeyA keys ch"></div>
<div class="KeyS keys ch"></div>
<div class="KeyD keys ch"></div>
<div class="KeyF keys ch"></div>
<div class="KeyG keys ch"></div>
<div class="KeyH keys ch"></div>
<div class="KeyJ keys ch"></div>
<div class="KeyK keys ch"></div>
<div class="KeyL keys ch"></div>
<div class="Semicolon keys ch"></div>
<div class="Quote keys ch"></div>
<div class="Enter keys">&ldca;</div>
<div class="ShiftLeft keys">Shift</div>
<div class="KeyZ keys ch"></div>
<div class="KeyX keys ch"></div>
<div class="KeyC keys ch"></div>
<div class="KeyV keys ch"></div>
<div class="KeyB keys ch"></div>
<div class="KeyN keys ch"></div>
<div class="KeyM keys ch"></div>
<div class="Comma keys ch"></div>
<div class="Period keys ch"></div>
<div class="Slash keys ch"></div>
<div class="Delete keys">Del</div>
<div class="ShiftRight keys">Shift</div>
<div class="ControlLeft keys">Ctrl</div>
<div class="MetaLeft keys">Win</div>
<div class="AltLeft keys">Alt</div>
<div class="Space keys">_____</div>
<div class="AltRight keys">Alt</div>
<div class="ControlRight keys">Ctrl</div>
<div class="ArrowLeft keys">&lArr;</div>
<div class="ArrowUp keys">&uArr;</div>
<div class="ArrowDown keys">&dArr;</div>
<div class="ArrowRight keys">&rArr;</div>`;

export default { data };
